/**
 * Copy the librats core into the package so the published tarball can build.
 *
 * In the repository this package sits at <repo>/react-native, and both platform
 * builds reach the core by walking up two levels — Android via add_subdirectory,
 * iOS via ../ios/build-xcframework.sh. In an installed package that path is
 * node_modules/, so a tarball without the core cannot build on either platform,
 * and npm cannot pack files from outside the package directory.
 *
 * So the core is vendored in on prepack. Run from the repo it refreshes
 * vendor/librats; run anywhere else (an already-published package) it does nothing,
 * which keeps `npm pack` on a consumer's machine from erasing what it shipped with.
 */
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const repoRoot = resolve(packageDir, '..')
const vendorDir = join(packageDir, 'vendor', 'librats')

// The root CMakeLists is what identifies a real checkout rather than an install.
if (!existsSync(join(repoRoot, 'CMakeLists.txt')) || !existsSync(join(repoRoot, 'src'))) {
  console.log('[vendor-core] not in a librats checkout; keeping vendor/ as shipped')
  process.exit(0)
}

rmSync(vendorDir, { recursive: true, force: true })
mkdirSync(join(vendorDir, 'ios'), { recursive: true })

// Everything the platform builds actually configure against. Deliberately a list
// rather than a copy of the whole repo: tests, examples, the other bindings and the
// benchmark tree are all irrelevant to a consumer and would multiply the tarball.
const files = [
  ['CMakeLists.txt', 'CMakeLists.txt'],
  ['LICENSE', 'LICENSE'],
  ['src', 'src'],
  ['ios/CMakeLists.txt', 'ios/CMakeLists.txt'],
  ['ios/module.modulemap', 'ios/module.modulemap'],
  ['ios/build-xcframework.sh', 'ios/build-xcframework.sh'],
]

for (const [from, to] of files) {
  const source = join(repoRoot, from)
  if (!existsSync(source)) {
    if (from === 'LICENSE') continue // optional
    throw new Error(`[vendor-core] missing ${from} — the core layout changed`)
  }
  cpSync(source, join(vendorDir, to), { recursive: true })
}

// A marker the platform builds can test for, and a note for anyone who finds this
// directory in node_modules and wonders whether it is safe to edit.
writeFileSync(
  join(vendorDir, 'VENDORED.md'),
  '# Vendored librats core\n\n' +
    'Generated by `scripts/vendor-core.mjs` on `npm pack`/`prepack`. Do not edit: ' +
    'changes belong in the repository root and are copied here at publish time.\n',
)

console.log(`[vendor-core] vendored the core into ${vendorDir.replace(packageDir + '/', '')}`)
